#
# This makefile was generated by pipe-gen
#

# List of output files associated with sinks
SINKS = \
    /home/mstockma/pipe-gen/src/test/workingDir/results/outputTextFile_1.txt \
    /home/mstockma/pipe-gen/src/test/workingDir/results/outputTextFile_0.txt \
    /home/mstockma/pipe-gen/src/test/workingDir/results/outputTextFile_2.txt \
    /home/mstockma/pipe-gen/src/test/workingDir/results/outputTextFile_3.txt \
    /home/mstockma/pipe-gen/src/test/workingDir/results/outputTextFile_4.txt \
    /home/mstockma/pipe-gen/src/test/workingDir/results/outputTextFile_5.txt \

# Define the phoney target 'all'. This targets each of the output files.
.PHONEY: all
all: $(SINKS)

# Dependency tree for: outputTextFile_1.txt
# SINK: 0
# ID: 0

# Module Name: cp
outputTextFile_1.txt : textFile_0.txt
	cp outputTextFile_1.txt outputTextFile_1.txt

# input 0
# SourceElement name='textFile'. (No make code written for sources)


# Dependency tree for: outputTextFile_0.txt
# SINK: 0
# ID: 1

# Module Name: cp
outputTextFile_1.txt : textFile_0.txt
	cp outputTextFile_1.txt outputTextFile_1.txt

# input 0
# SourceElement name='textFile'. (No make code written for sources)


# Dependency tree for: outputTextFile_2.txt
# SINK: 0
# ID: 2

# Module Name: cp
outputTextFile_1.txt : textFile_0.txt
	cp outputTextFile_1.txt outputTextFile_1.txt

# input 0
# SourceElement name='textFile'. (No make code written for sources)


# Dependency tree for: outputTextFile_3.txt
# SINK: 0
# ID: 3

# Module Name: cp
outputTextFile_1.txt : textFile_0.txt
	cp outputTextFile_1.txt outputTextFile_1.txt

# input 0
# SourceElement name='textFile'. (No make code written for sources)


# Dependency tree for: outputTextFile_4.txt
# SINK: 0
# ID: 4

# Module Name: cp
outputTextFile_1.txt : textFile_0.txt
	cp outputTextFile_1.txt outputTextFile_1.txt

# input 0
# SourceElement name='textFile'. (No make code written for sources)


# Dependency tree for: outputTextFile_5.txt
# SINK: 0
# ID: 5

# Module Name: cp
outputTextFile_1.txt : textFile_0.txt
	cp outputTextFile_1.txt outputTextFile_1.txt

# input 0
# SourceElement name='textFile'. (No make code written for sources)


